name: eshop_multivendor
description: eShop Multivendor App
publish_to: "none"

version: 2.9.2+32


environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.2
  firebase_messaging: ^15.0.0
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.15.0
  firebase_auth: ^5.0.0
  sms_autofill: ^2.3.1
  google_maps_flutter: ^2.2.2
  geolocator: ^12.0.0
  file_picker: ^8.0.3
  shimmer: ^3.0.0
  geocoding: ^3.0.0
  razorpay_flutter: ^1.3.0
  flutter_paystack: ^1.0.7
  flutter_html_to_pdf:
    git:
      url: https://github.com/mohammadhprp/flutter_html_to_pdf2
  permission_handler: ^11.2.1
  in_app_review: ^2.0.8
  firebase_dynamic_links: ^6.0.0
  open_filex: ^4.4.0
  provider: ^6.1.1
  share_plus: ^9.0.0
  firebase_core: ^3.0.0
  video_player: ^2.4.10
  flutter_svg: ^2.0.9
  youtube_player_flutter: ^8.1.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.4
  sqflite: ^2.3.2
  version: ^3.0.2
  flutter_downloader: ^1.9.1
  speech_to_text: ^6.1.1
  tuple: ^2.0.1
  lottie: ^3.0.0
  flutter_stripe: ^10.1.1
  flutter_widget_from_html: ^0.15.0
  # flutter_html: ^3.0.0-alpha.6
  my_fatoorah: ^3.1.0
  webview_flutter: ^4.4.2
  intl_phone_field: ^3.2.0
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.1
  flutter_styled_toast: ^2.2.1
  paytm_allinonesdk: ^1.2.1
  external_path: ^1.0.3
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  device_info_plus: ^10.1.0
  cached_network_image: ^3.3.1
  phonepe_payment_sdk: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^4.0.0


dependency_overrides:
  intl: ^0.18.1
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/animation/
    - lib/Language/
    - assets/eShop.db

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf
