// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyARTe5htvFenm-AwoVUOES3iwce8sjM',
    appId: '1:327324836622:web:252e7906b04fde8136ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    authDomain: 'eshop-multivendor-new.firebaseapp.com',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    measurementId: 'G-J7Y3R8EJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_1l5qdSvmWJ7MRj82U3_V4s6ymEprFdg',
    appId: '1:327324836622:android:47d0aca03bf12c3536ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    storageBucket: 'eshop-multivendor-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusENYY_9QM5nLi3lMJaCaECAJB2W-LhA',
    appId: '1:327324836622:ios:f4c05db96aa86bc636ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    androidClientId: '327324836622-0da9k42bkpmfgjbkji5a9l2lq37g0tvr.apps.googleusercontent.com',
    iosClientId: '327324836622-66keg8mgjde4hdd1g14uee9hbks5ngki.apps.googleusercontent.com',
    iosBundleId: 'wrteam.eshop.multivendor',
  );
}
